services:
  gateway-service:
    image: ghcr.io/${GITHUB_OWNER:-phamthanhlong100504-xpnd}/gateway-service:latest
    container_name: gateway-service
    restart: unless-stopped
    ports:
      - "8888:8888"
    mem_limit: 512m
    environment:
      JAVA_TOOL_OPTIONS: "-Djava.net.preferIPv4Stack=true -Xms128m -Xmx384m"
      IDENTITY_SERVICE_URL: "http://103.20.96.85:8081"
      PRACTICE_SERVICE_URL: "http://dts-practice-service:8087"
      PROGRESS_SERVICE_URL: "http://dts-progress:8083"
      MEDIA_SERVICE_URL: "http://103.20.96.85:8080"
      EXAMINATION_SERVICE_URL: "http://examination:8088"
      RESULT_SERVICE_URL: "http://dts-result:8080"
    networks:
      - dts-network

networks:
  dts-network:
    external: true
