server:
  port: 8888

jwt:
  secret: "dts_microservices_secret_key_for_jwt_verification_2026_super_secure_key_384_bits"

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Cho phép tự động tìm service qua Eureka
          lower-case-service-id: true
      # Cấu hình CORS cho phép Frontend (React/Vite) kết nối không bị chặn
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # Cấu hình Route chuyển tiếp request tới các Microservices bên dưới
      routes:
        # 1. Identity Service (Đăng nhập, phân quyền)
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**

        # 2. Content Builder Service (Xây dựng nội dung)
        - id: content-builder-service
          uri: lb://content-builder
          predicates:
            - Path=/api/v1/contents/**

        # 3. Examination Service (Thi thử)
        - id: examination-service
          uri: lb://examination
          predicates:
            - Path=/api/v1/exams/**

        # 4. Practice Service (Ôn luyện)
        - id: practice-service
          uri: lb://practice-service
          predicates:
            - Path=/api/v1/practices/**

        # 5. Progress Service (Theo dõi tiến độ)
        - id: progress-service
          uri: lb://progress-service
          predicates:
            - Path=/api/v1/progress/**


        # 7. Media Storage Service (Lưu hình ảnh, video, audio)
        - id: media-service
          uri: lb://media
          predicates:
            - Path=/api/v1/media/**

        # 8. Declaration Service (Định danh)
        - id: declaration-service
          uri: lb://declaration-service
          predicates:
            - Path=/api/v1/declarations/**

        # 9. Learning History Service (Lịch sử học)
        - id: learning-history-service
          uri: lb://learning-history-service
          predicates:
            - Path=/api/v1/history/**

        # 10. Tracking Service (Kết quả)
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/v1/tracking/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG

# Cấu hình Eureka Client
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
